var navs = [{
	"title": "藏品",
	"icon": "fa-cubes",
	"spread": true,
	"children": [{
		"title": "藏品种类",
		"icon": "&#xe641;",
		"href": "categary.html"
	}, {
		"title": "藏家管理",
		"icon": "&#xe63c;",
		"href": "collector.html"
	}, {
		"title": "藏品管理",
		"icon": "&#xe63c;",
		"href": "collection.html"
	}, {
		"title": "添加藏品",
		"icon": "&#xe63c;",
		"href": "collectionAdd.html"
	},{
		"title": "图片上传",
		"icon": "&#xe63c;",
		"href": "aTextUpload.html"
	},{
		"title": "上传Demo",
		"icon": "&#xe63c;",
		"href": "aTextUpload2.html"
	},{
		"title": "按钮",
		"icon": "&#xe641;",
		"href": "button.html"
	}, {
		"title": "表单",
		"icon": "&#xe63c;",
		"href": "form.html"
	}, {
		"title": "表格",
		"icon": "&#xe63c;",
		"href": "table.html"
	}, {
		"title": "导航",
		"icon": "&#xe609;",
		"href": "nav.html"
	}, {
		"title": "辅助性元素",
		"icon": "&#xe60c;",
		"href": "auxiliar.html"
	}]
}, {
	"title": "组件",
	"icon": "fa-cogs",
	"spread": false,
	"children": [{
		"title": "BTable",
		"icon": "fa-table",
		"href": "btable.html"
	}, {
		"title": "Navbar组件",
		"icon": "fa-navicon",
		"href": "navbar.html"
	}, {
		"title": "Tab组件",
		"icon": "&#xe62a;",
		"href": "tab.html"
	}, {
		"title": "Laytpl+Laypage",
		"icon": "&#xe628;",
		"href": "paging.html"
	}]
}, {
	"title": "第三方组件",
	"icon": "&#x1002;",
	"spread": false,
	"children": [{
		"title": "iCheck组件",
		"icon": "fa-check-square-o",
		"href": "icheck.html"
	}]
}, {
	"title": "地址本",
	"icon": "fa-address-book",
	"href": "",
	"spread": false,
	"children": [{
		"title": "Github",
		"icon": "fa-github",
		"href": "https://www.github.com/"
	}, {
		"title": "QQ",
		"icon": "fa-qq",
		"href": "http://www.qq.com/"
	}, {
		"title": "Fly社区",
		"icon": "&#xe609;",
		"href": "http://fly.layui.com/"
	}, {
		"title": "新浪微博",
		"icon": "fa-weibo",
		"href": "http://weibo.com/"
	}]
}, {
	"title": "这是一级导航",
	"icon": "fa-stop-circle",
	"href": "https://www.baidu.com",
	"spread": false
}, {
	"title": "其他",
	"icon": "fa-stop-circle",
	"href": "#",
	"spread": false,
	"children": [{
		"title": "子窗体中打开选项卡",
		"icon": "fa-github",
		"href": "cop.html"
	}]
}];